version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pug
      - POSTGRES_USER=pug
      - POSTGRES_PASSWORD=LhKWySLgbfRxtxn

  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8121
    volumes:
      - .:/code
    ports:
      - "8121:8121"
    environment:
      - POSTGRES_DB=pug
      - POSTGRES_USER=pug
      - POSTGRES_PASSWORD=LhKWySLgbfRxtxn
    depends_on:
      - db
    links:
      - db:db

