version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pug
      - POSTGRES_USER=pug
      - POSTGRES_PASSWORD=LhKWySLgbfRxtxn

  web:
    build: .
    container_name: backend-pug
    command: >
      sh -c "poetry run python manage.py migrate backend && poetry run python manage.py makemigrations && poetry run gunicorn --bind 0.0.0.0:8122 pug_project.wsgi"
    ports:
      - "8122:8122"
    environment:
      - POSTGRES_DB=pug
      - POSTGRES_USER=pug
      - POSTGRES_PASSWORD=LhKWySLgbfRxtxn
    depends_on:
      - db