# Generated by Django 4.1 on 2022-09-23 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('street_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_players_number', models.IntegerField(default=0)),
                ('actual_players_number', models.IntegerField(default=0)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_address', to='backend.address')),
            ],
        ),
        migrations.CreateModel(
            name='CourtDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courts_number', models.IntegerField()),
                ('hoops_number', models.IntegerField()),
                ('lightning', models.BooleanField()),
                ('surface', models.CharField(choices=[('Cement', 'Cement'), ('Concrete', 'Concrete'), ('Dirt', 'Dirt'), ('Grass', 'Grass'), ('Plastic', 'Plastic'), ('Rubber', 'Rubber'), ('Wood', 'Wood'), ('Other', 'Other')], default='Other', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.FloatField()),
                ('creation_date', models.DateTimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_rating', to='backend.court')),
            ],
        ),
        migrations.CreateModel(
            name='PlayingTimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('player_nick', models.CharField(max_length=20)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeframes', to='backend.court')),
            ],
        ),
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.court')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_details', to='backend.courtdetails'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_comment', to='backend.court')),
            ],
        ),
    ]
