# Generated by Django 4.1 on 2022-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtdetails',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courtdetails',
            name='rim_type',
            field=models.CharField(choices=[('Higher', 'Higher'), ('Lower', 'Lower'), ('Normal', 'Normal'), ('Various', 'Various')], default='Normal', max_length=10),
        ),
        migrations.AddField(
            model_name='courtdetails',
            name='type',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], default='Outdoor', max_length=10),
        ),
        migrations.AlterField(
            model_name='courtdetails',
            name='lightning',
            field=models.BooleanField(default=False),
        ),
    ]
