# Generated by Django 4.1 on 2022-09-24 13:59

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_courtdetails_public_courtdetails_rim_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtimage',
            name='image',
            field=models.ImageField(upload_to=backend.models.upload_to),
        ),
    ]
