# Generated by Django 4.1 on 2022-08-28 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_court_created_alter_playingtimeframe_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playingtimeframe',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
