# Generated by Django 4.1 on 2022-09-27 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_courtimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
