# Generated by Django 4.1 on 2022-09-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_rating_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.court'),
        ),
    ]
