# Generated by Django 4.1 on 2022-08-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_court_created_alter_playingtimeframe_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.address'),
        ),
        migrations.AlterField(
            model_name='court',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.courtdetails'),
        ),
    ]
