# Generated by Django 4.1 on 2022-09-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_court_address_alter_court_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_comment', to='backend.court'),
        ),
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_address', to='backend.address'),
        ),
        migrations.AlterField(
            model_name='court',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_details', to='backend.courtdetails'),
        ),
        migrations.AlterField(
            model_name='playingtimeframe',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_to_play_on', to='backend.court'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_rating', to='backend.court'),
        ),
    ]
