# Generated by Django 4.1 on 2022-09-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_comment_court_alter_court_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playingtimeframe',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeframes', to='backend.court'),
        ),
    ]
