# Generated by Django 4.1 on 2022-09-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_playingtimeframe_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='actual_players_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='court',
            name='expected_players_number',
            field=models.IntegerField(default=0),
        ),
    ]
