# Generated by Django 4.1 on 2022-09-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_comment_user_ip_rating_user_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.court'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='backend.court'),
        ),
    ]
