# Generated by Django 4.1 on 2022-09-27 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_rating_creation_date_alter_comment_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
