# Generated by Django 4.1 on 2022-09-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rating_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='expected_players_number',
        ),
        migrations.AlterField(
            model_name='court',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court', to='backend.address'),
        ),
        migrations.AlterField(
            model_name='court',
            name='details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court', to='backend.courtdetails'),
        ),
    ]
