# Generated by Django 4.1 on 2022-09-28 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_court_expected_players_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playingtimeframe',
            name='finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
