# Generated by Django 4.1 on 2022-09-28 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_playingtimeframe_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtimage',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.court'),
        ),
    ]
